config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  root to: "home#index"
  mount Sidekiq::Web => '/sidekiq'
  get  "elastic" => "home#elastic"
  get  "elastic_autocomplete" => "home#elastic_autocomplete"

  get  "solr" => "home#solr"

  get  "algolia" => "home#algolia"

  get  "materialized" => "home#materialized"
  get  "materialized_autocomplete" => "home#materialized_autocomplete"

  get  "benchmark" => "home#benchmark"
end

app/models/activity.rb
# frozen_string_literal: true
class Activity < ApplicationRecord
	has_many :activity_tags
  has_many :tags, through: :activity_tags
  has_one :activity_location
  has_one :location, through: :activity_location

  ## for Materilized View
  after_commit :refresh_view

  ## for ElasticSearch - searchkick
  searchkick text_start: [:title],
             suggest: [:title],
             settings: {index: {max_result_window: 10000}}

  ## for ElasticSearch - searchkick
  def search_data
    {
      title: title,
      about: about,
      start_months_old: start_months_old,
      end_months_old: end_months_old,
      camp: camp,
      drop_in: drop_in,
      date_night: date_night,
      indoor: indoor,
      outdoor: outdoor
    }
  end

  # ## for solr
  # searchable do
  #   text :title
  #   boolean :drop_in
  #   boolean :camp
  #   boolean :date_night
  #   boolean :indoor
  #   boolean :outdoor
  # end

  include AlgoliaSearch
  ## for algolia
  algoliasearch do
    attribute :title, :drop_in, :camp, :date_night, :indoor, :outdoor
  end

  def options
    options = []
    [:camp ,:drop_in, :date_night, :indoor, :outdoor].each{|x| options << x.to_s if send(x) }
    options
  end

private

  def refresh_view
     MaterializedSearchResult.refresh
  end
end

app/models/activity_location.rb
class ActivityLocation < ApplicationRecord
  belongs_to :activity
  belongs_to :location
end

app/models/activity_tag.rb
class ActivityTag < ApplicationRecord
	belongs_to :activity
	belongs_to :tag
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bench_mark_data.rb
class BenchMarkData < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
  has_one :activity_location
  has_one :activity, through: :activity_location

  # ## for solr
  # searchable do
  #   text :name
  # end
end

app/models/materialized_search_result.rb
# frozen_string_literal: true
# require 'textacular/searchable'
class MaterializedSearchResult < ApplicationRecord
  extend Textacular
  # extend Searchable(:title, :about)

  # We want to reference various models
  belongs_to :searchable, :polymorphic => true

  scope :camp, -> { self.search(searchable_camp: true) }
  scope :indoor, -> { self.search(searchable_indoor: true) }
  scope :outdoor, -> { self.search(searchable_outdoor: true) }
  scope :drop_in, -> { self.search(searchable_drop_in: true) }
  scope :date_night, -> { self.search(searchable_date_night: true) }

  # Search.new('query') to search for 'query'
  # across searchable models
  def self.new(query, options = {})
    query = query.to_s
    return [] if query.empty? && options.empty?
    return self.search(prefix_searchable(options)).map(&:searchable) if query.empty? && !options.empty?
    return self.search(query).map(&:searchable) if !query.empty? && options.empty?

    self.search(query).search(prefix_searchable(options)).map(&:searchable)
  end

  # Search records are never modified
  def readonly?; true; end

  # Our view doesn't have primary keys, so we need
  # to be explicit about how to tell different search
  # results apart; without this, we can't use :include
  # to avoid n + 1 query problems
  def hash; [searchable_id, searchable_type].hash; end
  def eql?(result)
    searchable_id == result.searchable_id and
      searchable_type == result.searchable_type
  end

  def self.refresh
    Scenic.database.refresh_materialized_view(table_name, concurrently: false)
  end

  def self.prefix_searchable(options)
    options.transform_keys{|k| "searchable_#{k}".to_sym }
  end
end

app/models/materialized_search_suggestion.rb
# frozen_string_literal: true
class MaterializedSearchSuggestion

  def self.seed
    [Activity].each do |cl|
      cl.find_each do |item|
        self.index_term(item.title)
        item.title.split.each { |t| self.index_term(t.gsub(".",""))}
      end
    end
  end

  def self.index_term(term)
    1.upto(term.length-1) do |n|
      prefix = term[0, n]
      $redis.zincrby "search-suggestions:#{prefix.downcase}", 1, term.downcase
    end
  end

  def self.terms_for(prefix)
    $redis.zrevrange "search-suggestions:#{prefix.downcase}", 0, 9
  end

  def self.clear
    keys = $redis.keys "search-suggestions:*"
    $redis.del(*keys) unless keys.empty?
  end
end

app/models/materilized_search_result.rb
# require 'textacular/searchable'
class MaterilizedSearchResult < ApplicationRecord
  extend Textacular
  # extend Searchable(:title, :about)

  # We want to reference various models
  belongs_to :searchable, :polymorphic => true

  scope :camp, -> { self.search(searchable_camp: true) }
  scope :indoor, -> { self.search(searchable_indoor: true) }
  scope :outdoor, -> { self.search(searchable_outdoor: true) }
  scope :drop_in, -> { self.search(searchable_drop_in: true) }
  scope :date_night, -> { self.search(searchable_date_night: true) }

  # Search.new('query') to search for 'query'
  # across searchable models
  def self.new(query, options = {})
    query = query.to_s
    return [] if query.empty?
    return self.search(query).map(&:searchable) if options == {}

    self.search(query).search(options).map(&:searchable)
  end

  # Search records are never modified
  def readonly?; true; end

  # Our view doesn't have primary keys, so we need
  # to be explicit about how to tell different search
  # results apart; without this, we can't use :include
  # to avoid n + 1 query problems
  def hash; [searchable_id, searchable_type].hash; end
  def eql?(result)
    searchable_id == result.searchable_id and
      searchable_type == result.searchable_type
  end

  def self.refresh
    Scenic.database.refresh_materialized_view(table_name, concurrently: false)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :activity_tags
  has_many :activities, through: :activity_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action do
    if Rails.env == 'development'
      Rack::MiniProfiler.authorize_request
    end
  end

  private

   def pagination_meta(object)
    {
      current_page: object.current_page,
      next_page: object.next_page,
      prev_page: object.previous_page,
      total_pages: object.total_pages,
      total_count: object.total_entries
    }
  end

  def render_results(activities)
    respond_to do |format|
      format.json do
       render(
         json: activities,
         serializer: ActiveModel::Serializer::CollectionSerializer,
         each_serializer: ActivitySerializer
       )
      end
      format.html
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@benchmark = BenchMarkData.last
	end

  def benchmark
    GenerateBenchmarkWorker.perform_async
    benchmark = BenchMarkData.last
    render json: {entries: benchmark.entries, result: benchmark.result.strip}.to_json
  end

  def elastic
    elastic_search = GetFacetsSearchResults.new(:elastic)
    @activities = elastic_search.call(params)
    render_results(@activities)
  end

  def elastic_autocomplete
    render json: Activity.search(params[:term], fields: [{title: :text_start}], limit: 5).map(&:title)
  end

  # def solr
  #   solr_search = GetFacetsSearchResults.new(:solr)
  #   @activities = solr_search.call(params)
  #   render_results(@activities)
  # end

  def algolia
    @activities = Kaminari.paginate_array(
      [Activity.last]
    ).page(1).per(2)
    render_results(@activities)
  end

  def materialized
    materialized_search = GetFacetsSearchResults.new(:materialized)
    @activities = materialized_search.call(params)
    render_results(@activities)
  end

  def materialized_autocomplete
    if params[:term]
      term = params[:term]
      result = MaterializedSearchSuggestion.terms_for(term)
    else
      result = []
    end
    render :json => result[0, 5]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/algolia.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-12 col-md-2">
      <% ['drop_in', 'date_night', 'camp', 'indoor', 'outdoor'].each do |option| %>

        <div class="form-check">
          <label class="form-check-label">
            <input class="form-check-input algolia-option" type="checkbox" id="<%= option %>" value="<%= option %>" data>
            <%= option %>
          </label>
        </div>
      <% end %>

    </div>

    <div class="col-xs-12 col-md-10" style="padding-left: 50px">
      <h2>Activity table - algolia (wip)</h2>

      <%= form_tag algolia_path, method: :get, class: 'algolia-autocomplete' do %>
        <fieldset class="form-group">
          <label for="formGroupExampleInput">Search <%= Activity.count%> activities via algolia</label>
          <div class="clear"></div>
          <div id="search-label"></div>
          <div class="clear"></div>

          <input type="text" name="q" id="algolia-search-input" placeholder="Search titles, about and tags" class="form-control ui-autocomplete-input">

        </fieldset>
      <% end %>


      <div class="clear"></div>
      <div class="spinner"></div>
      <div class="clear"></div>
      <table class="table table-sm table-hover">
        <thead>
          <tr>
            <th>Price</th>
            <th colspan="2">Title</th>
            <th>Options</th>
            <th class="text-xs-center">Tags</th>
          </tr>
        </thead>
        <tbody class='algolia-search-result'>
          <% @activities.each do |activity| %>
            <tr>
              <th scope="row"><%= activity.price %></th>
              <td colspan="2"><%= activity.title %></td>
              <td ><%= activity.options.join(', ') %></td>
              <td>
                <%= activity.tags.map(&:title).join(', ') %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @activities %>
    </div>
  </div>
</div>

app/views/home/elastic.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-12 col-md-2">
      <% ['drop_in', 'date_night', 'camp', 'indoor', 'outdoor'].each do |option| %>

        <div class="form-check">
          <label class="form-check-label">
            <input class="form-check-input elastic-option" type="checkbox" id="<%= option %>" value="<%= option %>" data>
            <%= option %>
          </label>
        </div>
      <% end %>

    </div>

    <div class="col-xs-12 col-md-10" style="padding-left: 50px">
      <h2>Activity table - Elastic</h2>

      <%= form_tag elastic_path, method: :get, class: 'elastic-autocomplete' do %>
        <fieldset class="form-group">
          <label for="formGroupExampleInput">Search <%= Activity.count%> activities with Elasticsearch via searchkick</label>
          <div class="clear"></div>
          <div id="search-label"></div>
          <div class="clear"></div>

          <input type="text" name="q" id="elastic-search-input" placeholder="Search titles, about and tags" class="form-control ui-autocomplete-input">

        </fieldset>
      <% end %>

      <% if @activities.suggestions.any? %>
        <p>Did you mean: <%= @activities.suggestions.first %></p>
      <% end %>
      <div class="clear"></div>
      <div class="spinner"></div>
      <div class="clear"></div>
      <table class="table table-sm table-hover">
        <thead>
          <tr>
            <th>Price</th>
            <th colspan="2">Title</th>
            <th>Options</th>
            <th class="text-xs-center">Tags</th>
          </tr>
        </thead>
        <tbody class='elastic-search-result'>
          <% @activities.each do |activity| %>
            <tr>
              <th scope="row"><%= activity.price %></th>
              <td colspan="2"><%= activity.title %></td>
              <td ><%= activity.options.join(', ') %></td>
              <td>
                <%= activity.tags.map(&:title).join(', ') %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @activities %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
	<h2>Benchmarking Search Options for Rails 5</h2>

	<a href="https://travis-ci.org/jaigouk/search-with" class="badge">
		<img src="https://img.shields.io/travis/jaigouk/search-with.svg" style="height: 20px;">
	</a>

  <a href="https://codebeat.co/projects/github-com-jaigouk-search-with" class="badge">
    <img alt="codebeat badge" src="https://codebeat.co/badges/8bb5880c-5ccf-456a-98cf-dbe65b722a95" style="height: 20px;"/>
  </a>

  <a href="https://www.codacy.com/app/jaigouk/search-with" class="badge">
    <img alt="codacy badge" src="https://img.shields.io/codacy/grade/646e5d50e84d4f97ada49a381ba61d16.svg" style="height: 20px;"/>
  </a>

  <a href="https://www.codacy.com/app/jaigouk/search-with" class="badge">
    <img alt="codacy badge" src="https://img.shields.io/codacy/coverage/646e5d50e84d4f97ada49a381ba61d16.svg" style="height: 20px;"/>
  </a>

  <br/>
  <br/>
  <h4>Motivation</h4>
  Because I wanted to know the basic heroku dyno's performance.

  <br/>
  <br/>
  <h4>Description</h4>

	<ul>
		<li>create a very simple app that has some "activity" records with various attributes</li>
		<li>a user should be able to check/uncheck boxes on the left filter panel</li>
		<li>activity records on the right activity table update via javascript.</li>
		<li>benchmarking data for using famous search methods</li>
	</ul>

  <h4>Result</h4>
  <div class="clear"></div>
  <div class="landing-spinner"></div>
  <div class="clear"></div>
  <p>It seems that the result depends on the network speed too because search services are running on seperate servers. </p>
  <br/>
  <% if @benchmark %>
    <pre class="language-bash benchmark-content">
      <code class="language-bash">
        <% @benchmark.entries.each do |entry| %>
        <%= entry.strip %><br/>
        <% end %>
        <%= @benchmark.result %>
      </code>
    </pre>
  <% end %>
  <button type="button" class="btn btn-secondary" id='update-benchmark'>Update the result</button>
</div>

app/views/home/materialized.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-12 col-md-2">
      <% ['drop_in', 'date_night', 'camp', 'indoor', 'outdoor'].each do |option| %>

        <div class="form-check">
          <label class="form-check-label">
            <input class="form-check-input materialized-option" type="checkbox" id="<%= option %>" value="<%= option %>" data>
            <%= option %>
          </label>
        </div>
      <% end %>

    </div>

    <div class="col-xs-12 col-md-10" style="padding-left: 50px">
      <h2>Activity table - materialized</h2>

      <form class="materialized-autocomplete" accept-charset="UTF-8">
        <input name="utf8" type="hidden" value="✓">
        <fieldset class="form-group">
          <label for="formGroupExampleInput">Search <%= Activity.count%> activities with Materialized View</label>
          <div class="clear"></div>
          <div id="materialized-search-label"></div>
          <div class="clear"></div>

          <input type="text" name="q" id="materialized-search-input" placeholder="Search titles, about and tags" class="form-control ui-autocomplete-input">

        </fieldset>
      </form>

      <div class="clear"></div>
      <div class="spinner"></div>
      <div class="clear"></div>
      <table class="table table-sm table-hover">
        <thead>
          <tr>
            <th>Price</th>
            <th colspan="2">Title</th>
            <th>Options</th>
            <th class="text-xs-center">Tags</th>
          </tr>
        </thead>
        <tbody class='materialized-search-result'>

        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/home/solr.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-12 col-md-2">
      <% ['drop_in', 'date_night', 'camp', 'indoor', 'outdoor'].each do |option| %>

        <div class="form-check">
          <label class="form-check-label">
            <input class="form-check-input solr-option" type="checkbox" id="<%= option %>" value="<%= option %>" data>
            <%= option %>
          </label>
        </div>
      <% end %>

    </div>

    <div class="col-xs-12 col-md-10" style="padding-left: 50px">
      <h2>Activity table - solr</h2>

      <%= form_tag solr_path, method: :get, class: 'solr-autocomplete' do %>
        <fieldset class="form-group">
          <label for="formGroupExampleInput">Search <%= Activity.count%> activities via Solr</label>
          <div class="clear"></div>
          <div id="search-label"></div>
          <div class="clear"></div>

          <input type="text" name="q" id="solr-search-input" placeholder="Search titles, about and tags" class="form-control ui-autocomplete-input">

        </fieldset>
      <% end %>


      <div class="clear"></div>
      <div class="spinner"></div>
      <div class="clear"></div>
      <table class="table table-sm table-hover">
        <thead>
          <tr>
            <th>Price</th>
            <th colspan="2">Title</th>
            <th>Options</th>
            <th class="text-xs-center">Tags</th>
          </tr>
        </thead>
        <tbody class='solr-search-result'>
          <% @activities.each do |activity| %>
            <tr>
              <th scope="row"><%= activity.price %></th>
              <td colspan="2"><%= activity.title %></td>
              <td ><%= activity.options.join(', ') %></td>
              <td>
                <%= activity.tags.map(&:title).join(', ') %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @activities %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jaigouk</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,900,300" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,300,600,700,900" rel="stylesheet" type="text/css">

  </head>

  <body>
    <div class="wrapper" id="wrapper">
      <%= render "/shared/header" %>
      <%= yield %>
      <%= render "/shared/footer" %>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
      <!--footer-->
      <section class="footer" id="footer">

        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <p>
                <a href="https://jaigouk.com" target="_blank">
                  &copy; <%= Time.now.year %> - jaigouk.com
                </a>
                &nbsp;&nbsp;|&nbsp;&nbsp;
                <a href="https://github.com/jaigouk/search-with" target="_blank">
                  source code
                </a>
              </p>
              </div>
            </div>
          </div>
      </section>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-dark bg-inverse" style="background-color: #563d7c;">

  <!-- Brand -->
  <a class="navbar-brand" href="/">SearchWith</a>

  <!-- Links -->
  <ul class="nav navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/elastic">Elastic Search</a>
    </li>
    <li class="nav-item">
     <a class="nav-link" href="/solr">Solr</a>
    </li>
    <li class="nav-item">
     <a class="nav-link" href="/algolia">Algolia</a>
    </li>
    <li class="nav-item">
     <a class="nav-link" href="/materialized" id="materialized-view-page">Materialized View</a>
    </li>
  </ul>
  </nav>
</header>